# Lab 1: Welcome to Python!


## Goals
Welcome to your first lab session! In this lab, you will gain hands-on experience with Python programming and learn how Python is used in Data Science.

The first goal of this lab is to ensure that your Python 3 environment is set up correctly and running without issues. If you encounter any problems, please let the tutor know.

This lab will also introduce you to writing your first Python programs, using both scripts and the interactive environment, and applying Python to work with real datasets.

In addition to basic Python concepts, you will begin using Python for basic data analysis tasks, such as loading data, exploring datasets, and performing simple operations that are common in Data Science workflows.

Even if some tasks seem simple, please complete them carefully, as they form the foundation for future labs.

As always, have fun and enjoy the rest of the class period!

## Submission

Name your Jupyter notebook `Group{group number}_week{number}.ipynb`. For example: Group1_week2.ipybn/pdf

## Let's get started!

## Part 1: Basic Python programming

### Loop

**Exercise 1:** Print First 10 natural numbers using while loop

**Expected output:**
````
0
1
2
3
4
5
6
7
8
9
10
````

In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### String

**Exercise 2**: Given 2 strings, s1 and s2, concat 2 strings
Given:
````
s1 = "Hello"
s2 = "World"
````
**Expected Output:**
````
    Hello World

````

In [1]:
s1 = "Hello"
s2 = "World"
result = s1 + " " + s2
print(result)

Hello World


**Exercise 3**: Removal all the characters other than integers from string
Given:
````
I am 25 years and 10 months old
````
**Expected Output:**
````
2510
````
**Hint: 
- list comprehension,
- Join(),
- isdigit()

In [14]:
text = "I am 25 years old and 10 months old"
result = "".join([char for char in text if char.isdigit()])
print(result)



2510


### Tuple

**Exercise 4**: Create a tuple with single item 50

In [16]:
tuple = (50,)
print(tuple)

(50,)


**Exercise 4**: Unpack the following tuple into 4 variables
````
aTuple = (10, 20, 30, 40)
````

**Expected output:**

````
aTuple = (10, 20, 30, 40)
# Your code
print(a) # should print 10
print(b) # should print 20
print(c) # should print 30
print(d) # should print 40
````

In [ ]:
atuple = (10, 20, 30, 40)
a, b, c, d, = atuple
print(a)
print(b)
print(c)
print(d)

10
20
30
40


**Exercise 5**: Swap the following two tuples
````
tuple1 = (11, 22)
tuple2 = (99, 88)
````
**Expected output:**
````
tuple1 = (99, 88)
tuple2 = (11, 22)
````

In [26]:
tuple1 = (11, 22)
tuple2 = (99, 88)
tuple1, tuple2 = tuple2, tuple1
print(tuple1)
print(tuple2)

(99, 88)
(11, 22)


### Set

**Exercise 6**: Add a list of elements to a given set
````
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = ["Blue", "Green", "Red"]
````
**Expected output:**

In set item order is not a concern
````
{'Green', 'Yellow', 'Black', 'Orange', 'Red', 'Blue'}
````
**Hint: use update()

In [29]:
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = {"Blue", "Green", "Red"}
sampleList.update(sampleSet)
print(sampleList)

{'Green', 'Yellow', 'Red', 'Orange', 'Blue', 'Black'}


**Exercise 7**: Returns a new set with all items from both sets by removing duplicates
````
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
````
**Expected output:**

````
{70, 40, 10, 50, 20, 60, 30}
````
Remember set is unordered so not necessary this will be the order of the item.

In [31]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set1.update(set(set2))
print(set1)

{70, 40, 10, 50, 20, 60, 30}


### Dictionaries

**Exercise 8**: Below are the two lists convert it into the dictionary
````
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
````
**Expected output:**

````
{'Ten': 10, 'Twenty': 20, 'Thirty': 30}````

In [32]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
convert = dict(zip(keys, values))
print(convert)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}


**Exercise 9**: Merge following two Python dictionaries into one
````
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
````
**Expected output:**

````
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
````

In [33]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
dict1.update(dict2)
print(dict1)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}


## Mixed parts

**Exercise 10:** Write a loop to find the factorial of any number
The factorial (symbol: !) means to multiply all whole numbers from our chosen number down to 1.

**For example:** calculate the factorial of 5

5! = 5 × 4 × 3 × 2 × 1 = 120

**Expected output:**
````
120
````

In [50]:
fact = 5
result = 1
for i in range(1, fact + 1):
    result *= i
print(f"{fact}! = {result}")


5! = 120


**Exercise 11:** Reverse a given integer number
Given:
````
76542
````

**Expected output:**
````
24567
````

In [56]:
n = 765432
rev = 0
while n > 0 :
    rev = rev * 10 + n % 10
    n //=10
print(rev)

234567


**Exercise 12:** Find the sum of the series 2 +22 + 222 + 2222 + .. n terms

Given:
````
number_of_terms = 5
````
So series will become 2 + 22 + 222 + 2222 + 22222

**Expected output:**
````
24690
````

In [24]:
number_of_terms = 5 
total = 0
term = 2
for i in range(number_of_terms) :
    total += term
    term = term * 10 + 2
print(total)

24690


**Exercise 13:** Create a function that can accept two arguments name and age and print its value

In [33]:
def person(name, age):
    print(f"Name: {name} Age: {age}")
person("Mab", 20)

Name: Mab Age: 20


**Exercise 14:** Write a function func1() such that it can accept a variable length of  argument and print all arguments value
````
func1(20, 40, 60)
func1(80, 100)
````

**Expected Output:**

After func1(20, 40, 60):
````
20
40
60
````

After func1(80, 100):
````
80
100
````

In [2]:
def func1(*args):
    print(args)
func1(20,40,50)
func1(80, 100)

(20, 40, 50)
(80, 100)


**Exercise 15:** Create a function showEmployee() in such a way that it should accept employee name, and it’s salary and display both, and if the salary is missing in function call it should show it as 9000

**Expected Output:**
````
showEmployee("Ben", 9000)
showEmployee("Ben")
````

Should Produce:
````
Employee Ben salary is: 9000
Employee Ben salary is: 9000
````

In [ ]:
def showEmployee(name, age = 9000):
    print(f"Employee {name} salary is: {age}")
showEmployee("Ben", 9000)
showEmployee("Ben")


Employee Ben salary is :9000
Employee Ben salary is :9000


**Exercise 16:** Given a two integer numbers return their product and  if the product is greater than 1000, then return their sum

Given:

````
number1 = 20
number2 = 30
````

Expected Output:

`````
The result is 600
````
Given:
````
number1 = 40
number2 = 30
````
Expected Output:
````
The result is 70
````

In [13]:
number1 = 40
number2 = 30
multiply = number1 * number2
if multiply > 1000:
    result = number1 + number2
    print(result)
else:
    result = multiply
    print(result)

70


**Exercise 17**: Given a two list of equal size create a set such that it shows the element from both lists in the pair

**Expected Output:**
````
First List  [2, 3, 4, 5, 6, 7, 8]
Second List  [4, 9, 16, 25, 36, 49, 64]
Result is  {(6, 36), (8, 64), (4, 16), (5, 25), (3, 9), (7, 49), (2, 4)}
````
**Hint: use zip()

In [16]:
list1 = [2,3,4,5,6,7,8]
list2 = [4,9,16,25,36,49,64]
result = list(zip(list1, list2))
print(result)

[(2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64)]


**Exercise 18:** Given a range of first 10 numbers, Iterate from start number to the end number and print the sum of the current number and previous number

Reference article for help:
- [Python range() function](https://pynative.com/python-range-function/)
- [Calculate sum and average in Python](https://pynative.com/python-program-to-calculate-sum-and-average-of-numbers/)

**Expected Output:**
````
Printing current and previous number sum in a given range(10)
Current Number 0 Previous Number  0  Sum:  0
Current Number 1 Previous Number  0  Sum:  1
Current Number 2 Previous Number  1  Sum:  3
Current Number 3 Previous Number  2  Sum:  5
Current Number 4 Previous Number  3  Sum:  7
Current Number 5 Previous Number  4  Sum:  9
Current Number 6 Previous Number  5  Sum:  11
Current Number 7 Previous Number  6  Sum:  13
Current Number 8 Previous Number  7  Sum:  15
Current Number 9 Previous Number  8  Sum:  17
````

In [33]:
previous_number = 0
for i in range(10):
    sum = i + previous_number
    print("Current Number", i, "Previous Number", previous_number, "Sum: ", sum)
    previous_number = i

Current Number 0 Previous Number 0 Sum:  0
Current Number 1 Previous Number 0 Sum:  1
Current Number 2 Previous Number 1 Sum:  3
Current Number 3 Previous Number 2 Sum:  5
Current Number 4 Previous Number 3 Sum:  7
Current Number 5 Previous Number 4 Sum:  9
Current Number 6 Previous Number 5 Sum:  11
Current Number 7 Previous Number 6 Sum:  13
Current Number 8 Previous Number 7 Sum:  15
Current Number 9 Previous Number 8 Sum:  17


**Exercise 19**: Delete set of keys from Python Dictionary
Given:
````
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}
keysToRemove = ["name", "salary"]
````
**Expected output:**

````
{'city': 'New york', 'age': 25}
````

In [35]:
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}
keysToRemove = ["name", "salary"]

for key in keysToRemove:
    sampleDict.pop(key, None)
print(sampleDict)

{'age': 25, 'city': 'New york'}


**Exercise 20:** Given a string, display only those characters which are present at an even index number.
For example str = "pynative" so you should display ‘p’, ‘n’, ‘t’, ‘v’.

Reference article for help: Python Input and Output

**Expected Output:**
````
Orginal String is  pynative
Printing only even index chars
p
n
t
v
````

In [36]:
str = "pynative"
for i in range(0, len(str), 2):
    print(str[i])


p
n
t
v


**Exercise 21:** Given a list of numbers, return True if first and last number of a list is same

**Expected Output:**
````
Given list is  [10, 20, 30, 40, 10]
result is True
Given list is  [10, 20, 30, 40, 50]
result is False
````

In [42]:
numbers = [10, 20, 30, 40, 10]
if numbers[0] == numbers[-1]:
    print(True)
else:
    print(False)

True


**Exercise 22:** Given a list of numbers, Iterate it and print only those numbers which are divisible of 5

**Expected Output:**
````
Given list is  [10, 20, 33, 46, 55]
Divisible of 5 in a list
10
20
55
````


In [47]:
numbers = [10, 20, 33, 46, 55]
for i in numbers:
    if i % 5 == 0:
        print(i)

10
20
55


**Exercise 23:** Return the total count of sub-string “Emma” appears in the given string

Given string is “Emma is good developer. Emma is a writer”

**Expected Output:**
````
Emma appeared 2 times
````

In [49]:
text = "Emma is good devloper. Emma is a write"
count = text.count("Emma")
print(f"Emma appeared {count} times" )

Emma appeared 2 times


**Exercise 24:** Print the following pattern
````
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5
````

In [70]:
n = 5
for i in range(1, n + 1):
    for j in range(i):
        print(i, end= " ")
    print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


**Exercise 25:** Print downward Half-Pyramid Pattern with Star (asterisk)

````
* * * * *  
* * * *  
* * *  
* *  
*
````

In [91]:
n = 5
for i in range(n, 0, -1):
    for j in range(i):
        print("*", end= " ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 


**Exercise 26:** Write a function called exponent(base, exp) that returns an int value of base raises to the power of exp.
Note here exp is a non-negative integer, and the base is an integer.

**Expected Output:**

Case 1:

base = 2
exponent = 5

2 raises to the power of 5 is: 32 i.e. (2 *2 * 2 *2 *2 = 32)

Case 2:

base = 5
exponent = 4

5 raises to the power of 4 is: 625 i.e. (5 *5 * 5 *5 = 625)

In [92]:
def exponent(base, exp):
    return base ** exp
exponent(2, 5)


32

## Part 2: Python for Data science

import pandas as pd

df = pd.read_csv("salary.csv")
df.head()


**Discussion 1**:
````
1. Why do we load data instead of typing it manually?
2. What does each row represent?
3. What does each column represent?
4. Why do we look at the first few rows?
````

**Answer 1**:
````
1. Because datasets are usually huge, typing manually is very time-consuming and prone to errors.
2. Each row represents a record, observation.
3. Each column represents attribute, variable of the dataset.
4. To quickly check the data without needing to print the whole dataset that takes time.
````

In [ ]:
pip install pandas


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [21]:
import pandas as pd

df = pd.read_csv("salary.csv")
# df.head()
df.shape
# df.columns

(21672, 16)

**Discussion 2**:
````
1.What does one row represent in this dataset?
2. What does one column represent?
3. Why is it important to know the number of rows and columns before analysis?
4. How many observations are in the dataset?
5. Which columns are numeric? Which are categorical?
````

**Answer 2**:
````
1. The row in this dataset represent one measurement for one industry, in one year, for one business size group .
2. One column represents the attribute like year, industry_code_ANZSIC, industry_name_ANZSIC.
3. So we can specify how big the dataset is.
4. (21672, 16)
5. Numeric columns: year
   Categorical: industry_code_ANZSIC, industry_name_ANZSIC, rme_size_grp, variable, value
````

In [25]:
# df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21672 entries, 0 to 21671
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   year                  21672 non-null  int64  
 1   industry_code_ANZSIC  21672 non-null  object 
 2   industry_name_ANZSIC  21672 non-null  object 
 3   rme_size_grp          21672 non-null  object 
 4   variable              21672 non-null  object 
 5   value                 21672 non-null  object 
 6   unit                  21672 non-null  object 
 7   Unnamed: 7            0 non-null      float64
 8   Unnamed: 8            0 non-null      float64
 9   Unnamed: 9            41 non-null     float64
 10  Unnamed: 10           41 non-null     object 
 11  Unnamed: 11           41 non-null     object 
 12  Unnamed: 12           41 non-null     object 
 13  Unnamed: 13           41 non-null     object 
 14  Unnamed: 14           41 non-null     object 
 15  Unnamed: 15        

**Discussion 3**:
````
1. Why is knowing data types important in data analysis?
2. What problems can happen if data types are incorrect?
3. Are there any missing values?
4. Which columns might need cleaning?
````

**Answer 3**:
````
1. Because data types decide which operation we can perform.
2. Numeric can be stored as string, cannot calculate average, min, max, Date can stored as string and cannot sort by time.
3. Unnamed: 7, Unnamed: 8 are missing values.
4. Value coulumn: shows as object and it should be numeric
   Unnamed: 7 and Unnamed 8 missing values.
````

In [26]:
df.describe()

year  Unnamed: 7  Unnamed: 8   Unnamed: 9
count  21672.000000         0.0         0.0    41.000000
mean    2017.500000         NaN         NaN  2022.268293
std        4.031222         NaN         NaN     0.448575
min     2011.000000         NaN         NaN  2022.000000
25%     2014.000000         NaN         NaN  2022.000000
50%     2017.500000         NaN         NaN  2022.000000
75%     2021.000000         NaN         NaN  2023.000000
max     2024.000000         NaN         NaN  2023.000000

**Discussion 4**:
````
1. What does average (mean) tell us about data?
2. Why might min and max be misleading sometimes?
3. Which variable has the highest average?
4. Are there any unusual values?
````

**Answer 5**:
````
1. Show the typical value of numeric data.
2. Min and max only show extreme values, not the overall distribution. They can be misleading if there are outliers or errors.
3. Unnamed: 9.
4. Yes, Unnamed 7 to Unnamed 9 has no values.
````

In [31]:
df["value"] = pd.to_numeric(df["value"], errors="coerce")
df_filtered = df[df["value"].notna()]
df_filtered.shape


(21289, 16)

**Discussion 5**:
````
1. Why might we want to remove some rows from a dataset?
2. What is the difference between cleaning data and losing data?
3. How many rows were removed?
````

**Answer 5**:
````
1. Some rows contains invalid or unusable data.
2. Cleanind data is about making data clean by removing unusable or invalid data, removing errors and converting type while losing data is accidentally remove the useful data.
3. Before cleaning: 21,672 rows After cleaning: 21,289 rows so 383 rows has been removed.
````